In [2]:
import numpy as np
from sklearn.neighbors import kneighbors_graph
# https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.kneighbors_graph.html
from sklearn.datasets import load_iris

In [12]:
iris_data = load_iris(return_X_y=True)

In [13]:
X_iris, y_iris = iris_data

In [15]:
print(X_iris[:10], y_iris[:10], sep="\n")

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]
[0 0 0 0 0 0 0 0 0 0]


In [25]:
G = kneighbors_graph(X[:15], n_neighbors=2)

In [31]:
adjacent_matrix = G.toarray()

In [64]:
def get_knn_graph(X, k=5):
    G = kneighbors_graph(X, n_neighbors=k)
    adjacent_matrix = G.toarray()
    n = len(X)
    list_of_neighbors = [[] for i in range(n)]
    for i in range(n):
        for j in range(n):
            if adjacent_matrix[i][j] > 0:
                list_of_neighbors[i].append(j)
    return list_of_neighbors

In [65]:
def coarse_graph(G):
    pass

In [66]:
def iterative_refinement(G):
    pass

In [67]:
def compute_gradient(points):
    pass